apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  jwt-secret: MQIcz3NPwbcYPOHtHT
  mongo-uri: mongodb+srv://1111:1111@cluster0.yxewx.mongodb.net/civcommerce?retryWrites=true&w=majority
  merchant-id: 4zrxz2qrmzkgdrh8
  public-key: xsn7srybnxznr7h3
  private-key: 858a39926ffecdd12edcdef4e6790fcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: sourikg/civi-backend:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: mongo-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: jwt-secret
        - name: BRAINTREE_MERCHANT_ID
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: merchant-id
        - name: BRAINTREE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: public-key
        - name: BRAINTREE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: private-key
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 5000
  selector:
    app: api